export interface Stop {
	createdAt: string
	docking_bay_type: string
	has_abusive_parking: string
	has_audio_stop_info: string
	has_bench: string
	has_cover: string
	has_crossing: string
	has_crosswalk: string
	has_electricity: string
	has_flag: string
	has_flat_access: string
	has_h2oa_signage: string
	has_lighting: string
	has_mupi: string
	has_network_map: string
	has_pip_audio: string
	has_pip_real_time: string
	has_pip_realtime: string
	has_pip_static: string
	has_pole: string
	has_pole_frame: string
	has_schedules: string
	has_shelter: string
	has_sidewalk: string
	has_stop_sign: string
	has_tactile_access: string
	has_tactile_pavement: string
	has_tactile_schedules: string
	has_trash_bin: string
	has_wide_access: string
	id: string
	is_locked: boolean
	jurisdiction: string
	last_accessibility_check: string
	last_infrastructure_check: null | string
	last_infrastructure_maintenance: null | string
	last_schedules_check: string
	last_schedules_maintenance: string
	last_stop_sign_check: string
	last_stop_sign_maintenance: string
	latitude: number
	locality: string
	longitude: number
	media_ids: string[]
	municipality_id: string
	name: string
	name_new: string
	near_airport: boolean
	near_bike_parking: boolean
	near_bike_sharing: boolean
	near_boat: boolean
	near_car_parking: boolean
	near_fire_station: boolean
	near_health_clinic: boolean
	near_historic_building: boolean
	near_hospital: boolean
	near_light_rail: boolean
	near_police_station: boolean
	near_school: boolean
	near_shopping: boolean
	near_subway: boolean
	near_train: boolean
	near_transit_office: boolean
	near_university: boolean
	notes: string
	operational_status: string
	parent_station: string
	pip_real_time_code: string
	platform_code: string
	shelter_code: string
	shelter_frame_area_cm: string
	shelter_maintainer: string
	short_name: string
	short_name_auto: boolean
	sidewalk_type: string
	stop_access_type: string
	stop_sign_maintainer: string
	tts_name: string
	updatedAt: string
	wheelchair_boarding: string
	zones_ids: string[]
}
